version: "3"

tasks:
  default:
    cmds:
      - go run cmd/main.go
    silent: true

  container:build:
    cmds:
      - podman build -t tg-bumblebee-bot:latest .
    silent: true

  container:run:
    cmds:
      - podman run --env-file .env tg-bumblebee-bot:latest
    silent: true
